name: Interactive iOS Simulator Session

on:
  workflow_dispatch:

jobs:
  start-interactive-session:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install tmate
        run: brew install tmate

      # --- THIS IS THE NEW STEP THAT SOLVES THE PASSWORD PROBLEM ---
      - name: Setup Passwordless SSH
        run: |
          # Generate a new, passwordless SSH key pair (id_rsa and id_rsa.pub)
          ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
          
          # Copy the public key to the list of keys that are allowed to log in
          cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
          
          # Set the correct permissions for the authorized_keys file
          chmod 600 ~/.ssh/authorized_keys
          
          echo "Passwordless SSH for localhost has been configured."

      - name: Start VNC Server and Establish Tunnel
        run: |
          # Start and configure the VNC server
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -restart -agent -privs -all
          VNC_PASSWORD='123456'
          echo "VNC Password is: $VNC_PASSWORD"
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -users $(whoami) -access -on -privs -all -setvnclegacy -vnclegacy yes -setvncpw -vncpw "$VNC_PASSWORD"
          
          # Start tmate and get connection strings
          echo "Starting tmate tunnel..."
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready

          # Print connection options
          echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
          echo "!!!               CONNECT USING ONE OF THESE                !!!"
          echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
          echo "!!! To connect via your Web Browser (more reliable):        !!!"
          tmate -S /tmp/tmate.sock display -p '#{tmate_web}'
          echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

      - name: Keep Session Alive
        run: |
          echo "Session is active. Connect using the details from the previous step."
          sleep 21000